import { Space, Button } from '@lotus/ripple';

export function WrapSpaceDemo() {
    return <Space wrap>
        <Button theme="solid" type="secondary">按钮</Button>
        <Button theme="solid" type="secondary">按钮</Button>
        <Button theme="solid" type="secondary">按钮</Button>
        <Button theme="solid" type="secondary">按钮</Button>
        <Button theme="solid" type="secondary">按钮</Button>
        <Button theme="solid" type="secondary">按钮</Button>
        <Button theme="solid" type="secondary">按钮</Button>
        <Button theme="solid" type="secondary">按钮</Button>
        <Button theme="solid" type="secondary">按钮</Button>
        <Button theme="solid" type="secondary">按钮</Button>
    </Space>;
}
