import { TypographyTitle } from '@lotus/ripple';

export function TypographyTitleDemo() {
    return <div>
        <TypographyTitle heading={1}>一级标题</TypographyTitle>
        <TypographyTitle heading={2}>二级标题</TypographyTitle>
        <TypographyTitle heading={3}>三级标题</TypographyTitle>
        <TypographyTitle heading={4}>四级标题</TypographyTitle>
        <TypographyTitle heading={5}>五级标题</TypographyTitle>
        <TypographyTitle heading={6}>六级标题</TypographyTitle>
    </div>;
}
